title: Alex Larsen
author: The same
subtitle: A minimal jekyll theme

url: "https://alex0112.github.io"
baseurl: ""

footer_url: "https://github.com/alex0112"
footer_text: "Theme by pro-panda"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
